//! Unlock authentication: scrypt-hashed passphrase + optional TOTP (RFC
//! 6238). Stored in `<dir>/egress-auth.json` (0600) — the seatbelt/bwrap
//! profile denies gapped panes read access to this file. Direct port
//! of `src/main/authlock.js`, which this file is pinned against two ways:
//! byte-for-byte against `tests/auth_fixtures.json`'s `scrypt[]` array
//! (generated by Node's real `crypto.scryptSync`), and behaviorally against
//! `test/authlock.test.js`'s `describe('enrollTotp() active-factor guard')`
//! block (TOME-005) — see the `#[cfg(test)] mod tests` below for both.
//!
//! TOTP's own crypto (HMAC-SHA1/base32) lives in `totp.rs`, exactly like
//! the JS split between `authlock.js` and `./lib/totp.js`.
//!
//! ## What's deliberately NOT here
//! `authlock.js` also owns a module-level `unlocked` flag
//! (`isUnlocked`/`markUnlocked`) — the app-session "is the user logged in
//! right now" bit. That state is cross-cutting session state, not
//! credential/verification logic, and `state.rs`'s `AppState.locked` field
//! already exists as its Rust home (see that field's own doc comment,
//! which names this exact split as the plan). This file owns only "is this
//! passphrase/code correct", matching this slice's file ownership
//! boundary (`state.rs` belongs to a different slice) and giving the
//! integrator one obvious place to flip `AppState.locked` — right after a
//! successful [`AuthLock::verify_passphrase`]/[`AuthLock::verify_totp`] —
//! rather than two.
//!
//! ## Storage-path-agnostic by design
//! [`AuthLock::load`] takes a directory, not a hardcoded Tauri path,
//! mirroring `initAuth(userData)`'s parameter exactly — the integrator
//! wires it to `app_data_dir()` (or any other directory, for example a temp dir in
//! tests) without this file needing to know Tauri exists.
//!
//! ## Secret-at-rest: why tests never touch the real OS keychain
//! `authlock.js` wraps the TOTP secret with Electron's `safeStorage`, which
//! is unwired outside a real Electron process — `test/authlock.test.js`
//! has a comment explaining that this is *why* its tests are hermetic:
//! `safeStorage` destructures to `undefined` under vitest, every call site
//! already wraps it in try/catch, and so every test there exercises the
//! plaintext-fallback path for free, by accident of the runtime.
//!
//! Rust has no equivalent accident to lean on: the `keyring` crate talks to
//! the real macOS Keychain / Linux Secret Service whether or not the
//! caller is `cargo test`. Running the real thing under test would, on
//! this very machine, pop a Keychain-access prompt (or hang one, headless)
//! and write a real `tech.abantu.tome`/`totp` credential into the
//! *developer's own* login keychain on every test run — a persistent,
//! security-relevant side effect a test suite must never cause by
//! accident. So secret-at-rest storage is abstracted behind the private
//! [`SecretProtector`] trait: production code (`AuthLock::load`) uses the
//! real [`KeyringProtector`], and `#[cfg(test)]` injects a hermetic fake
//! via `AuthLock::load_with_protector` instead — deliberately reproducing,
//! by an explicit seam, the isolation the JS suite gets for free.
//!
//! ## Electron `enc:v1:` blobs vs. this build's own `keyring:v1` marker
//! Electron's `safeStorage` stores a per-app AES key in the OS keychain and
//! keeps the TOTP secret on disk as ciphertext (`enc:v1:<base64>`). The
//! `keyring` crate models a *different* scheme entirely: it stores the
//! secret itself directly in the OS credential store, with no ciphertext
//! on disk at all. The two are not the same format and this build cannot
//! derive Electron's per-app key, so a stored secret beginning `enc:v1:` is
//! permanently unreadable here by construction — [`AuthLock::unprotect_secret`]
//! recognizes the prefix and fails closed (verification simply returns
//! `false`) rather than mis-decoding ciphertext as base32 or panicking.
//! Re-enrollment UX for that failed-closed case is out of scope for this
//! phase (tracked as a later migration phase). The no-keychain-available
//! fallback, by contrast, **is** wire-compatible both ways: both this file
//! and `authlock.js` write the bare base32 string with no prefix at all
//! when no OS credential store is available, so a headless-Linux-written
//! file reads back identically regardless of which implementation wrote
//! it.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use rand::Rng;
use serde::{Deserialize, Serialize};
use subtle::ConstantTimeEq;

use crate::totp::{b32decode, b32encode, hotp, now_ms};

/// Minimum passphrase length, counted the way JS's `pass.length` counts it
/// — UTF-16 code units, not Unicode scalar values or bytes (a passphrase of
/// four astral-plane emoji is length 8 in JS, since each is a surrogate
/// pair; `.encode_utf16().count()` below reproduces that exactly rather
/// than the shorter count `.chars().count()` would give). Purely a UX
/// minimum-length gate, not a cryptographic parameter, but ported exactly
/// anyway since it's one line.
pub const MIN_PASSPHRASE_LEN: usize = 8;

const AUTH_FILE_NAME: &str = "egress-auth.json";

// scrypt cost parameters. Two log-N values now exist, versioned through
// `AuthState.log_n` (F-06, the security assessment's crypto-hardening
// finding):
//
// - `SCRYPT_LOG_N` (2^16) is what `set_passphrase` uses for NEW
//   enrollments. Node's documented default (2^14) is a GPU-trivial
//   offline barrier against a stolen `egress-auth.json`; 2^16 keeps
//   interactive login comfortably fast while making brute force ~4x more
//   expensive per guess.
// - `SCRYPT_LOG_N_LEGACY` (2^14) is Node's *documented default* for
//   `crypto.scryptSync(password, salt, keylen)` called with no `options`
//   object — exactly how `authlock.js` calls it (`scryptSync(pass, salt,
//   32)`). Every pre-existing Electron-written hash was computed at these
//   params, and a file whose `log_n` field is absent (all of them) must
//   still VERIFY, so verification falls back to this value. Bumping the
//   verification params outright would lock every existing user out of
//   their own vault — the versioned scheme below is what makes the bump
//   safe.
//
// NOT this crate's own `Params::RECOMMENDED` (log_n 17), which would
// produce hashes cross-language-incompatible with either value above.
// Legacy hashes are pinned byte-for-byte against
// `tests/auth_fixtures.json`'s `scrypt[]` array in the
// `scrypt_hash_matches_fixtures` test below (written first, per this
// slice's brief, since a mismatch there breaks every passphrase set by the
// Electron build).
const SCRYPT_LOG_N: u8 = 16; // N = 2^16 = 65536 — new enrollments
const SCRYPT_LOG_N_LEGACY: u8 = 14; // N = 2^14 = 16384 — legacy files verify at this
const SCRYPT_R: u32 = 8;
const SCRYPT_P: u32 = 1;
const SCRYPT_DKLEN: usize = 32;

// ---- TOTP secret-at-rest markers (see module doc comment) ----
const TOTP_ENC_PREFIX_ELECTRON: &str = "enc:v1:";
const TOTP_KEYRING_MARKER: &str = "keyring:v1";
const KEYRING_SERVICE: &str = "tech.abantu.tome";
const KEYRING_ACCOUNT: &str = "totp";

// ---- login throttling ----
// scrypt at default cost is tens of milliseconds — a speed bump, not a
// wall, against IPC-speed brute force. Back off exponentially after
// repeated failures (5th failure -> 30s, doubling each failure after,
// capped at 30 minutes), per purpose, so the lock screen and a single
// pane's unlock throttle independently. Success resets the counter. Ported
// as-is from `authlock.js`'s `attempts` map.
const BACKOFF_AFTER: u32 = 5;
const BACKOFF_BASE_MS: u64 = 30_000;
const BACKOFF_MAX_MS: u64 = 30 * 60_000;

/// On-disk shape of `egress-auth.json` — deliberately the same flat field
/// names as `authlock.js`'s `auth` object (`{ salt, hash, totp? }`) so a
/// file either implementation writes reads back identically in the other
/// (salt/hash are always plain scrypt hex, never encrypted, so this holds
/// regardless of which side wrote the file). `#[serde(default)]`
/// everywhere so a partial or hand-edited file (or a pre-TOTP Electron
/// file with no `totp` key at all) loads as "field absent" rather than
/// failing to parse — matching `initAuth`'s any-error-becomes-null
/// permissiveness.
///
/// Deliberately does not derive `Debug`/`Display`: this struct's fields
/// are exactly the two things the security invariants say must never be
/// logged (the passphrase hash, and the TOTP secret when no keychain is
/// available to protect it) — leaving `Debug` off means an accidental
/// `{:?}` of the whole state fails to *compile* rather than silently
/// working. Tests below assert on individual fields instead of the struct
/// as a whole.
#[derive(Serialize, Deserialize, Default)]
struct AuthState {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    salt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    hash: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    totp: Option<TotpState>,
    /// The scrypt log-N the stored hash was computed with. `None` means
    /// "legacy default" (`SCRYPT_LOG_N_LEGACY`, what every Electron-built
    /// file carries) — `verify_passphrase` falls back to that value, so
    /// old files keep verifying after `set_passphrase` moved on to
    /// stronger params. Written as `Some(SCRYPT_LOG_N)` on every new
    /// enrollment; the JS original knows nothing about this field and
    /// (being serde-tolerant) ignores it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    log_n: Option<u8>,
}

#[derive(Serialize, Deserialize, Default)]
struct TotpState {
    #[serde(default)]
    secret: String,
    #[serde(default)]
    active: bool,
}

/// `{ configured, totp }` — mirrors `authlock.js`'s `authStatus()` return
/// shape exactly (field names match, so a future IPC command can return
/// this directly as JSON).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct AuthStatus {
    pub configured: bool,
    pub totp: bool,
}

/// Result of a successful [`AuthLock::enroll_totp`] — the plaintext
/// secret (for rendering a QR code / manual-entry string to the user) plus
/// the `otpauth://` URI, mirroring `authlock.js`'s `enrollTotp()` return
/// shape (`{ secret, uri }`) field-for-field.
#[derive(Debug, Clone, Serialize)]
pub struct TotpEnrollment {
    pub secret: String,
    pub uri: String,
}

/// Errors from [`AuthLock`]'s fallible operations. `Display` produces the
/// exact same user-facing text `authlock.js`'s thrown `Error.message`
/// values do (`test/authlock.test.js` pins `'Active second factor
/// present.'` verbatim), so an integrator can surface `.to_string()`
/// directly, matching every existing `egress:*`/`auth:*` handler's
/// `{ ok: false, error: err.message }` shape.
#[derive(Debug)]
pub enum AuthError {
    PassphraseTooShort,
    ActiveFactorPresent,
    Io(std::io::Error),
    Serde(serde_json::Error),
}

impl std::fmt::Display for AuthError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AuthError::PassphraseTooShort => write!(
                f,
                "Passphrase must be at least {MIN_PASSPHRASE_LEN} characters."
            ),
            AuthError::ActiveFactorPresent => write!(f, "Active second factor present."),
            AuthError::Io(e) => write!(f, "{e}"),
            AuthError::Serde(e) => write!(f, "{e}"),
        }
    }
}

impl std::error::Error for AuthError {}

impl From<std::io::Error> for AuthError {
    fn from(e: std::io::Error) -> Self {
        AuthError::Io(e)
    }
}

impl From<serde_json::Error> for AuthError {
    fn from(e: serde_json::Error) -> Self {
        AuthError::Serde(e)
    }
}

/// Where a TOTP secret's bytes physically live once "protected" (as
/// opposed to living as plaintext base32 in `AuthState.totp.secret`
/// itself). See the module doc comment for why this indirection exists at
/// all: it's the seam that keeps `#[cfg(test)]` off the real OS keychain.
trait SecretProtector: Send + Sync {
    /// Best-effort availability probe, consulted before every wrap
    /// attempt rather than cached — mirrors `authlock.js`'s `canEncrypt()`,
    /// which is also called fresh each time rather than trusted as a
    /// sticky fact (the keychain can become available/unavailable across
    /// the process's lifetime).
    fn available(&self) -> bool;
    /// Store `secret`, returning whether it succeeded.
    fn store(&self, secret: &str) -> bool;
    /// Retrieve a previously stored secret, if any.
    fn retrieve(&self) -> Option<String>;
}

/// Production [`SecretProtector`]: the OS credential store via the
/// `keyring` crate (Keychain on macOS, Secret Service on Linux). Every
/// method collapses any error into "unavailable"/`None` — matching
/// `authlock.js`'s `canEncrypt()` try/catch, which treats a locked
/// keychain, a missing Secret Service, or any other failure identically to
/// "no keychain": fall back to plaintext rather than error out.
struct KeyringProtector;

impl SecretProtector for KeyringProtector {
    fn available(&self) -> bool {
        keyring::Entry::new(KEYRING_SERVICE, KEYRING_ACCOUNT).is_ok()
    }

    fn store(&self, secret: &str) -> bool {
        keyring::Entry::new(KEYRING_SERVICE, KEYRING_ACCOUNT)
            .and_then(|e| e.set_password(secret))
            .is_ok()
    }

    fn retrieve(&self) -> Option<String> {
        keyring::Entry::new(KEYRING_SERVICE, KEYRING_ACCOUNT)
            .ok()?
            .get_password()
            .ok()
    }
}

/// Passphrase + TOTP credential store for one `egress-auth.json`. Not
/// `Clone`/`Copy` (holds a `Box<dyn SecretProtector>`); wrap in whatever
/// synchronization the integrator's `AppState` needs (this file has no
/// opinion — see the module doc comment on why session-lock state is
/// deliberately not here either).
pub struct AuthLock {
    path: PathBuf,
    state: AuthState,
    protector: Box<dyn SecretProtector>,
    attempts: HashMap<String, Backoff>,
}

struct Backoff {
    fails: u32,
    next_at_ms: u64,
}

/// Pure backoff-delay curve, extracted from `record_failure` so the
/// doubling-then-capping math is testable without depending on real
/// elapsed wall-clock time between two calls. `fails` is clamped before
/// shifting (`.min(20)`) purely to keep `1u64 << exp` from ever
/// overflowing/panicking for a pathologically large fail count — by
/// `exp = 20` the raw value is already ~17x past `BACKOFF_MAX_MS` and gets
/// clamped by the trailing `.min` regardless, so this changes no observable
/// output vs. JS's `2 ** n` (which saturates to `Infinity` instead, then
/// `Math.min`s down to the same cap either way).
fn backoff_delay_ms(fails: u32) -> u64 {
    if fails < BACKOFF_AFTER {
        return 0;
    }
    let exp = (fails - BACKOFF_AFTER).min(20);
    BACKOFF_BASE_MS
        .saturating_mul(1u64 << exp)
        .min(BACKOFF_MAX_MS)
}

impl AuthLock {
    /// Loads (or, on any read/parse failure, initializes fresh — matching
    /// `initAuth`'s `try { ... } catch { auth = null }`) the auth state
    /// from `<dir>/egress-auth.json`. `dir` is caller-supplied, not a
    /// hardcoded Tauri path — see the module doc comment.
    pub fn load(dir: impl AsRef<Path>) -> Self {
        Self::load_with_protector(dir, Box::new(KeyringProtector))
    }

    /// Test-only seam: like [`Self::load`], but with an injected
    /// [`SecretProtector`] instead of the real OS keychain. Not `pub` —
    /// nothing outside this module's own tests should construct an
    /// `AuthLock` with a non-default protector.
    fn load_with_protector(dir: impl AsRef<Path>, protector: Box<dyn SecretProtector>) -> Self {
        let path = dir.as_ref().join(AUTH_FILE_NAME);
        let state = std::fs::read_to_string(&path)
            .ok()
            .and_then(|text| serde_json::from_str(&text).ok())
            .unwrap_or_default();
        Self {
            path,
            state,
            protector,
            attempts: HashMap::new(),
        }
    }

    fn save(&self) -> Result<(), AuthError> {
        let json = serde_json::to_string(&self.state)?;
        std::fs::write(&self.path, json)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&self.path, std::fs::Permissions::from_mode(0o600))?;
        }
        Ok(())
    }

    /// `{ configured: !!auth?.hash, totp: !!auth?.totp?.active }` — see
    /// `authlock.js`'s `authStatus()`.
    pub fn status(&self) -> AuthStatus {
        AuthStatus {
            configured: self.state.hash.is_some(),
            totp: self.state.totp.as_ref().is_some_and(|t| t.active),
        }
    }

    /// Sets/replaces the passphrase (fresh random salt every call — this
    /// is also how a passphrase *change* works, same as JS: unconditional
    /// overwrite, no "already configured" guard here). That guard belongs
    /// to the IPC handler layer in the JS original (`index.js`'s
    /// `egress:setup` checks `authStatus().configured` before ever calling
    /// `setPassphrase`) — reproduced here as an omission on purpose, to
    /// keep this file's boundary exactly where `authlock.js`'s is.
    pub fn set_passphrase(&mut self, pass: &str) -> Result<(), AuthError> {
        if pass.encode_utf16().count() < MIN_PASSPHRASE_LEN {
            return Err(AuthError::PassphraseTooShort);
        }
        let mut salt_bytes = [0u8; 16];
        rand::rng().fill_bytes(&mut salt_bytes);
        let salt = hex_encode(&salt_bytes);
        // New enrollments hash at the stronger current params (F-06) and
        // record which params, so a future bump never invalidates them.
        let hash = hex_encode(&scrypt_hash_with(
            pass.as_bytes(),
            salt.as_bytes(),
            SCRYPT_LOG_N,
        ));
        self.state.salt = Some(salt);
        self.state.hash = Some(hash);
        self.state.log_n = Some(SCRYPT_LOG_N);
        self.migrate_totp_secret(); // re-wrap any legacy plaintext TOTP secret on this write
        self.save()
    }

    /// `false` if no passphrase is configured, else a constant-time
    /// comparison of a freshly computed scrypt hash against the stored
    /// one (`authlock.js`'s `verifyPassphrase` + Node's `timingSafeEqual`).
    pub fn verify_passphrase(&self, pass: &str) -> bool {
        let (Some(salt), Some(hash_hex)) = (&self.state.salt, &self.state.hash) else {
            return false;
        };
        let Some(expected) = hex_decode(hash_hex) else {
            return false;
        };
        // Verify at the params the hash was STORED with, not whatever this
        // build currently enrolls at — a legacy file (no `log_n`) was
        // hashed by Node at 2^14 and must still match (F-06).
        let log_n = self.state.log_n.unwrap_or(SCRYPT_LOG_N_LEGACY);
        let got = scrypt_hash_with(pass.as_bytes(), salt.as_bytes(), log_n);
        bool::from(got[..].ct_eq(&expected[..]))
    }

    /// Enrolls a new TOTP secret. Refuses to clobber an already-active
    /// factor (TOME-005: `enrollTotp`/`confirmTotp` both sit on
    /// `OPEN_CHANNELS`, reachable pre-auth, so an unauthenticated caller
    /// must not be able to roll a secret only they know over the owner's
    /// active one and confirm it out from under them). First-time
    /// enrollment, and re-enrollment before the first `confirm_totp`
    /// succeeds, are both unaffected — matching `authlock.js` exactly.
    pub fn enroll_totp(&mut self) -> Result<TotpEnrollment, AuthError> {
        if self.totp_active() {
            return Err(AuthError::ActiveFactorPresent);
        }
        let mut raw = [0u8; 20];
        rand::rng().fill_bytes(&mut raw);
        let secret = b32encode(&raw);
        let stored = self.protect_secret(&secret);
        self.state.totp = Some(TotpState {
            secret: stored,
            active: false,
        });
        self.save()?;
        let uri = format!("otpauth://totp/tome?secret={secret}&issuer=tome");
        Ok(TotpEnrollment { secret, uri })
    }

    /// Verifies `code` against the enrolled secret with a ±1 step (±30s)
    /// window, matching `authlock.js`'s `verifyTotp`. Returns `false` (not
    /// an error) for "no TOTP enrolled", "secret unreadable" (an
    /// undecryptable Electron blob, or a keyring lookup that failed), and
    /// "wrong code" alike — verification has exactly one honest outcome
    /// space, `bool`, same as the JS original.
    pub fn verify_totp(&self, code: &str) -> bool {
        let Some(t) = &self.state.totp else {
            return false;
        };
        let Some(plain) = self.unprotect_secret(&t.secret) else {
            return false;
        };
        let secret = b32decode(&plain);
        let step = now_ms() / 30_000;
        // Constant-time comparison (F-06): a 6-digit code is only ~20 bits,
        // and although the per-purpose attempt throttling is the real
        // brute-force wall, `==` on the digit string hands a timing oracle
        // to a caller who can measure rejections. `subtle::ConstantTimeEq`
        // is already a dependency of this file, so the stronger compare is
        // free; a length-mismatched `code` compares unequal without
        // leaking where the difference was.
        for counter in [step.saturating_sub(1), step, step + 1] {
            let candidate = hotp(&secret, counter);
            if bool::from(candidate.as_bytes().ct_eq(code.as_bytes())) {
                return true;
            }
        }
        false
    }

    /// Confirms enrollment: verifies `code` and, only on success, flips
    /// `active`. Matches `authlock.js`'s `confirmTotp` — `Ok(false)` for a
    /// wrong code (not an error), `Err` only for a save failure.
    pub fn confirm_totp(&mut self, code: &str) -> Result<bool, AuthError> {
        if !self.verify_totp(code) {
            return Ok(false);
        }
        if let Some(t) = self.state.totp.as_mut() {
            t.active = true;
        }
        self.migrate_totp_secret();
        self.save()?;
        Ok(true)
    }

    pub fn totp_active(&self) -> bool {
        self.state.totp.as_ref().is_some_and(|t| t.active)
    }

    /// How many milliseconds until `purpose`'s next attempt is allowed;
    /// `0` means "attempt now". Matches `authlock.js`'s `throttleRetryIn`.
    pub fn throttle_retry_in(&self, purpose: &str) -> u64 {
        let next_at = self
            .attempts
            .get(purpose)
            .map(|a| a.next_at_ms)
            .unwrap_or(0);
        next_at.saturating_sub(now_ms())
    }

    /// Records a failed attempt for `purpose`, arming/advancing its
    /// backoff per [`backoff_delay_ms`]. Matches `authlock.js`'s
    /// `recordFailure`.
    pub fn record_failure(&mut self, purpose: &str) {
        let entry = self.attempts.entry(purpose.to_string()).or_insert(Backoff {
            fails: 0,
            next_at_ms: 0,
        });
        entry.fails += 1;
        let delay = backoff_delay_ms(entry.fails);
        if delay > 0 {
            entry.next_at_ms = now_ms() + delay;
        }
    }

    /// Clears `purpose`'s backoff state entirely. Matches `authlock.js`'s
    /// `recordSuccess`.
    pub fn record_success(&mut self, purpose: &str) {
        self.attempts.remove(purpose);
    }

    // ---- TOTP secret-at-rest wrapping (see module doc comment) ----

    fn protect_secret(&self, plain: &str) -> String {
        if self.protector.available() && self.protector.store(plain) {
            TOTP_KEYRING_MARKER.to_string()
        } else {
            plain.to_string()
        }
    }

    /// `None` means "unrecoverable" (an Electron blob this build can't
    /// decrypt, or a keyring marker whose backing entry is gone) — the
    /// caller (only ever [`Self::verify_totp`]) treats that as "verify
    /// fails", matching `authlock.js`'s `unprotectSecret`/`verifyTotp`
    /// try/catch ("encrypted secret but no keychain to unwrap it -> return
    /// false").
    fn unprotect_secret(&self, stored: &str) -> Option<String> {
        if stored.starts_with(TOTP_ENC_PREFIX_ELECTRON) {
            None
        } else if stored == TOTP_KEYRING_MARKER {
            self.protector.retrieve()
        } else {
            Some(stored.to_string()) // this build's own plaintext fallback, or JS's identical one
        }
    }

    /// One-way upgrade: re-wraps a legacy/fallback plaintext secret via
    /// the protector if it's available now (called after every
    /// state-changing save, same call sites as JS's `migrateTotpSecret`:
    /// `set_passphrase` and `confirm_totp`). Never touches an
    /// already-protected marker or an Electron blob — the latter is a
    /// decrypt-only-fallback dead end by construction, exactly like JS's
    /// "if the keychain disappears we can still *read* an encrypted secret
    /// but new writes stay plaintext rather than pretending to be
    /// encrypted" comment describes for its own mirror-image case.
    fn migrate_totp_secret(&mut self) {
        let Some(t) = self.state.totp.as_mut() else {
            return;
        };
        let is_plain =
            t.secret != TOTP_KEYRING_MARKER && !t.secret.starts_with(TOTP_ENC_PREFIX_ELECTRON);
        if is_plain && self.protector.available() && self.protector.store(&t.secret) {
            t.secret = TOTP_KEYRING_MARKER.to_string();
        }
    }
}

/// scrypt with this file's pinned parameters (see the `SCRYPT_*` consts).
/// `salt` is whatever bytes the caller passes — critically, callers pass
/// the *hex string's own UTF-8 bytes*, not hex-decoded bytes: Node's
/// `scryptSync(password, saltHexString, keylen)` treats a string `salt`
/// argument as UTF-8 text, not as hex to decode, so a 32-character hex
/// string becomes a 32-byte salt, not the 16 bytes it represents. Getting
/// this backwards is the single most likely way to fail the fixture pin
/// silently (both sides would produce *a* hash, just the wrong one) —
/// `scrypt_hash_matches_fixtures` below exists specifically to catch it.
/// scrypt at an explicit log-N — the general form both [`SCRYPT_LOG_N`]
/// (enrollment) and [`SCRYPT_LOG_N_LEGACY`] (legacy verification) go
/// through (F-06). See the constants' doc comment for why two params
/// values exist at all.
fn scrypt_hash_with(pass: &[u8], salt: &[u8], log_n: u8) -> [u8; SCRYPT_DKLEN] {
    let params = scrypt::Params::new(log_n, SCRYPT_R, SCRYPT_P)
        .expect("static scrypt params are always valid");
    let mut out = [0u8; SCRYPT_DKLEN];
    scrypt::scrypt(pass, salt, &params, &mut out)
        .expect("32-byte output is within scrypt's valid range");
    out
}

/// Legacy-params scrypt — kept as the named wrapper the fixture-pinning
/// test below exercises, since `tests/auth_fixtures.json`'s hashes were
/// all generated by Node at its default (2^14). Only the `#[cfg(test)]`
/// suite (and the legacy-verification test) use it — production hashes
/// through [`scrypt_hash_with`] at an explicit log-N.
#[cfg(test)]
fn scrypt_hash(pass: &[u8], salt: &[u8]) -> [u8; SCRYPT_DKLEN] {
    scrypt_hash_with(pass, salt, SCRYPT_LOG_N_LEGACY)
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        let _ = write!(s, "{b:02x}");
    }
    s
}

/// Strict hex decode (unlike `totp::b32decode`, this fails closed on any
/// malformed input rather than skipping bad characters) — used only to
/// turn a stored `hash` field back into bytes for comparison. `None` on
/// odd length or a non-hex-digit character; callers treat that as
/// "verification fails" rather than panicking on a corrupted file.
fn hex_decode(s: &str) -> Option<Vec<u8>> {
    if !s.len().is_multiple_of(2) {
        return None;
    }
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len() / 2);
    for chunk in bytes.chunks_exact(2) {
        let hi = (chunk[0] as char).to_digit(16)?;
        let lo = (chunk[1] as char).to_digit(16)?;
        out.push(((hi << 4) | lo) as u8);
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---- hermetic SecretProtector fakes (see module doc comment on why
    // the real KeyringProtector never runs under `cargo test`) ----

    /// Always unavailable — forces the plaintext fallback path, exactly
    /// the path `test/authlock.test.js` exercises under vitest (its own
    /// comment: `safeStorage` destructures to `undefined` outside a real
    /// Electron process).
    struct NullProtector;
    impl SecretProtector for NullProtector {
        fn available(&self) -> bool {
            false
        }
        fn store(&self, _secret: &str) -> bool {
            false
        }
        fn retrieve(&self) -> Option<String> {
            None
        }
    }

    /// Always available, in-memory — exercises the "keyring present" path
    /// deterministically, without touching the real OS keychain.
    struct FakeProtector(std::sync::Mutex<Option<String>>);
    impl FakeProtector {
        fn new() -> Self {
            Self(std::sync::Mutex::new(None))
        }
    }
    impl SecretProtector for FakeProtector {
        fn available(&self) -> bool {
            true
        }
        fn store(&self, secret: &str) -> bool {
            *self.0.lock().unwrap() = Some(secret.to_string());
            true
        }
        fn retrieve(&self) -> Option<String> {
            self.0.lock().unwrap().clone()
        }
    }

    fn fresh_lock() -> (tempfile::TempDir, AuthLock) {
        let dir = tempfile::tempdir().expect("tempdir");
        let lock = AuthLock::load_with_protector(dir.path(), Box::new(NullProtector));
        (dir, lock)
    }

    // ---- cross-language fixture pin (write this one first — a mismatch
    // here means every passphrase the Electron build ever hashed breaks
    // silently in the rewrite) ----

    const FIXTURES_JSON: &str = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/auth_fixtures.json"
    ));

    #[derive(serde::Deserialize)]
    struct ScryptFixture {
        pass: String,
        salt: String,
        hash: String,
        #[serde(rename = "N")]
        n: u32,
        r: u32,
        p: u32,
        dklen: usize,
    }

    #[derive(serde::Deserialize)]
    struct Fixtures {
        scrypt: Vec<ScryptFixture>,
    }

    fn load_fixtures() -> Fixtures {
        serde_json::from_str(FIXTURES_JSON).expect("auth_fixtures.json parses")
    }

    /// Exercises the raw `scrypt` crate call directly, using each
    /// fixture's own declared N/r/p/dklen (not this file's hardcoded
    /// consts) — proves the fundamental mechanism (salt-as-UTF8-string-
    /// bytes, `Params::new(log_n, r, p)`) is right, independent of this
    /// file's own parameter choice.
    #[test]
    fn scrypt_raw_matches_fixtures() {
        let fx = load_fixtures();
        assert!(
            !fx.scrypt.is_empty(),
            "fixture file has no scrypt[] entries"
        );
        for f in &fx.scrypt {
            let log_n = f.n.trailing_zeros() as u8;
            assert_eq!(
                1u32 << log_n,
                f.n,
                "fixture N={} is not a power of two",
                f.n
            );
            let params = scrypt::Params::new(log_n, f.r, f.p).expect("fixture params are valid");
            let mut out = vec![0u8; f.dklen];
            scrypt::scrypt(f.pass.as_bytes(), f.salt.as_bytes(), &params, &mut out)
                .expect("scrypt succeeds for fixture params");
            assert_eq!(
                hex_encode(&out),
                f.hash,
                "pass={:?} salt={:?}",
                f.pass,
                f.salt
            );
        }
    }

    /// Exercises this file's own `scrypt_hash` helper — the one
    /// `set_passphrase`/`verify_passphrase` actually call — against the
    /// same fixtures, catching a mistake in `SCRYPT_LOG_N`/`R`/`P`/`DKLEN`
    /// that `scrypt_raw_matches_fixtures` above can't (it uses the
    /// fixture's own params, not this file's consts).
    #[test]
    fn scrypt_hash_matches_fixtures() {
        let fx = load_fixtures();
        for f in &fx.scrypt {
            let got = scrypt_hash(f.pass.as_bytes(), f.salt.as_bytes());
            assert_eq!(
                hex_encode(&got),
                f.hash,
                "pass={:?} salt={:?}",
                f.pass,
                f.salt
            );
        }
    }

    // ---- hex helpers ----

    #[test]
    fn hex_round_trips() {
        let bytes: Vec<u8> = (0..=255).collect();
        assert_eq!(hex_decode(&hex_encode(&bytes)).unwrap(), bytes);
    }

    #[test]
    fn hex_decode_rejects_malformed_input() {
        assert!(hex_decode("abc").is_none()); // odd length
        assert!(hex_decode("zz").is_none()); // not hex digits
    }

    // ---- passphrase: set/verify happy path, wrong pass, too-short guard ----

    #[test]
    fn set_passphrase_rejects_too_short() {
        let (_dir, mut lock) = fresh_lock();
        let err = lock.set_passphrase("short").unwrap_err();
        assert_eq!(err.to_string(), "Passphrase must be at least 8 characters.");
        assert!(!lock.status().configured);
    }

    #[test]
    fn set_passphrase_length_boundary_is_inclusive() {
        let (_dir, mut lock) = fresh_lock();
        assert!(
            lock.set_passphrase("1234567").is_err(),
            "7 chars must still be rejected"
        );
        assert!(
            lock.set_passphrase("12345678").is_ok(),
            "exactly 8 chars must be accepted"
        );
    }

    #[test]
    fn set_passphrase_length_counts_utf16_code_units_like_js() {
        // "🔐" (U+1F510) is outside the Basic Multilingual Plane, so JS's
        // `pass.length` (UTF-16 code units) counts each occurrence as 2,
        // not 1 — four of them is JS length 8 (meets MIN_PASSPHRASE_LEN)
        // even though it's only 4 Unicode scalar values / `.chars()`.
        // Proves `.encode_utf16().count()` was the right choice over
        // `.chars().count()` (which would wrongly reject this as length 4).
        let (_dir, mut lock) = fresh_lock();
        let astral_passphrase = "\u{1F510}\u{1F510}\u{1F510}\u{1F510}";
        assert_eq!(astral_passphrase.chars().count(), 4);
        assert_eq!(astral_passphrase.encode_utf16().count(), 8);
        assert!(lock.set_passphrase(astral_passphrase).is_ok());
        assert!(lock.verify_passphrase(astral_passphrase));
    }

    #[test]
    fn set_passphrase_then_verify_roundtrip() {
        let (_dir, mut lock) = fresh_lock();
        lock.set_passphrase("hunter2-fake").unwrap();
        assert!(lock.status().configured);
        assert!(lock.verify_passphrase("hunter2-fake"));
        assert!(!lock.verify_passphrase("wrong-passphrase"));
    }

    #[test]
    fn verify_passphrase_false_when_unconfigured() {
        let (_dir, lock) = fresh_lock();
        assert!(!lock.status().configured);
        assert!(!lock.verify_passphrase("anything12"));
    }

    #[test]
    fn set_passphrase_uses_fresh_salt_each_call() {
        let (_dir, mut lock) = fresh_lock();
        lock.set_passphrase("hunter2-fake").unwrap();
        let first_hash = lock.state.hash.clone();
        lock.set_passphrase("hunter2-fake").unwrap();
        let second_hash = lock.state.hash.clone();
        assert_ne!(
            first_hash, second_hash,
            "same passphrase, different salt, must differ"
        );
        assert!(lock.verify_passphrase("hunter2-fake"));
    }

    // ---- F-06: versioned scrypt params - new enrollments hash stronger,
    // legacy files still verify at Node's default - ----

    #[test]
    fn new_enrollments_record_log_n_16_and_verify_at_it() {
        let (_dir, mut lock) = fresh_lock();
        lock.set_passphrase("hunter2-fake").unwrap();
        assert_eq!(
            lock.state.log_n,
            Some(SCRYPT_LOG_N),
            "enrollment must stamp the params it hashed at"
        );
        assert!(lock.verify_passphrase("hunter2-fake"));
        assert!(!lock.verify_passphrase("wrong-passphrase"));
    }

    #[test]
    fn legacy_enrollment_without_a_stored_log_n_verifies_at_legacy_params() {
        // Simulates an Electron-written egress-auth.json: salt+hash only,
        // no log_n field. Must still verify — bumping verification params
        // outright would lock every pre-existing user out (F-06).
        let (_dir, mut lock) = fresh_lock();
        let salt = hex_encode(&[7u8; 16]);
        let hash = hex_encode(&scrypt_hash(b"legacy-passphrase", salt.as_bytes()));
        lock.state.salt = Some(salt);
        lock.state.hash = Some(hash);
        assert_eq!(lock.state.log_n, None);
        assert!(lock.verify_passphrase("legacy-passphrase"));
        assert!(!lock.verify_passphrase("wrong-passphrase"));
    }

    #[test]
    fn verify_totp_rejects_an_odd_length_code_without_panicking() {
        // The constant-time compare must be length-tolerant: a caller can
        // send any string, and a mismatch must read as false rather than
        // panic (subtle's slice ct_eq compares lengths as part of the
        // choice).
        let (_dir, mut lock) = fresh_lock();
        lock.state.totp = Some(TotpState {
            secret: "PLAINBASE32SECRETXXX".to_string(),
            active: true,
        });
        for bad in ["", "1", "12345", "1234567", "abcdef"] {
            assert!(!lock.verify_totp(bad), "{bad:?} must verify false");
        }
    }

    #[test]
    fn saved_file_has_0600_permissions() {
        let (dir, mut lock) = fresh_lock();
        lock.set_passphrase("hunter2-fake").unwrap();
        use std::os::unix::fs::PermissionsExt;
        let meta = std::fs::metadata(dir.path().join(AUTH_FILE_NAME)).unwrap();
        assert_eq!(meta.permissions().mode() & 0o777, 0o600);
    }

    // ---- TOME-005: enrollTotp() active-factor guard — ported from
    // test/authlock.test.js's `describe('enrollTotp() active-factor guard')` ----

    #[test]
    fn enroll_totp_first_time_succeeds() {
        let (_dir, mut lock) = fresh_lock();
        let enrollment = lock.enroll_totp().unwrap();
        assert!(!enrollment.secret.is_empty());
        assert!(
            enrollment
                .secret
                .chars()
                .all(|c| c.is_ascii_uppercase() || ('2'..='7').contains(&c)),
            "secret {} is not [A-Z2-7]+",
            enrollment.secret
        );
        assert_eq!(
            enrollment.uri,
            format!(
                "otpauth://totp/tome?secret={}&issuer=tome",
                enrollment.secret
            )
        );
    }

    #[test]
    fn enroll_totp_reenroll_before_confirm_succeeds() {
        let (_dir, mut lock) = fresh_lock();
        let first = lock.enroll_totp().unwrap();
        let second = lock.enroll_totp().unwrap();
        assert!(second
            .secret
            .chars()
            .all(|c| c.is_ascii_uppercase() || ('2'..='7').contains(&c)));
        assert_ne!(second.secret, first.secret);
    }

    #[test]
    fn enroll_totp_refuses_when_active() {
        let (_dir, mut lock) = fresh_lock();
        let enrollment = lock.enroll_totp().unwrap();
        let raw = b32decode(&enrollment.secret);
        let code = hotp(&raw, now_ms() / 30_000);
        assert!(lock.confirm_totp(&code).unwrap());
        let err = lock.enroll_totp().unwrap_err();
        assert_eq!(err.to_string(), "Active second factor present.");
    }

    // ---- confirm/verify: wrong code, ±1 window ----

    #[test]
    fn confirm_totp_wrong_code_fails_and_stays_inactive() {
        let (_dir, mut lock) = fresh_lock();
        let enrollment = lock.enroll_totp().unwrap();
        let raw = b32decode(&enrollment.secret);
        // 10 steps (5 minutes) away is well outside the ±1 window — a
        // deterministically wrong code, not a fixed literal that could
        // (astronomically rarely) coincide with the real one.
        let wrong_code = hotp(&raw, now_ms() / 30_000 + 10);
        assert!(!lock.confirm_totp(&wrong_code).unwrap());
        assert!(!lock.totp_active());
    }

    #[test]
    fn verify_totp_rejects_a_wrong_code_deterministically() {
        let (_dir, mut lock) = fresh_lock();
        let enrollment = lock.enroll_totp().unwrap();
        let raw = b32decode(&enrollment.secret);
        let step = now_ms() / 30_000;
        let real_code = hotp(&raw, step);
        // A code from 10 steps away (5 minutes) is well outside the ±1 window.
        let wrong_code = hotp(&raw, step + 10);
        assert_ne!(
            real_code, wrong_code,
            "test secret produced a coincidental collision"
        );
        assert!(!lock.verify_totp(&wrong_code));
        assert!(lock.confirm_totp(&real_code).unwrap());
    }

    #[test]
    fn verify_totp_accepts_adjacent_step_window() {
        let (_dir, mut lock) = fresh_lock();
        let enrollment = lock.enroll_totp().unwrap();
        let raw = b32decode(&enrollment.secret);
        let step = now_ms() / 30_000;
        assert!(lock.confirm_totp(&hotp(&raw, step)).unwrap());
        assert!(lock.verify_totp(&hotp(&raw, step - 1)));
        assert!(lock.verify_totp(&hotp(&raw, step + 1)));
        assert!(!lock.verify_totp(&hotp(&raw, step + 2)));
    }

    #[test]
    fn verify_totp_false_when_not_enrolled() {
        let (_dir, lock) = fresh_lock();
        assert!(!lock.verify_totp("123456"));
    }

    // ---- Electron enc:v1: blobs: never decrypt, fail closed ----

    #[test]
    fn electron_blob_fails_closed() {
        let (_dir, mut lock) = fresh_lock();
        lock.state.totp = Some(TotpState {
            secret: "enc:v1:not-actually-decryptable-here==".to_string(),
            active: true,
        });
        assert!(lock.totp_active()); // active flag itself is still readable
        assert!(!lock.verify_totp("000000")); // fails closed, never panics/misdecodes
    }

    // ---- secret-at-rest protection + migration ----

    #[test]
    fn enroll_with_available_protector_stores_marker_not_plaintext() {
        let dir = tempfile::tempdir().unwrap();
        let mut lock = AuthLock::load_with_protector(dir.path(), Box::new(FakeProtector::new()));
        let enrollment = lock.enroll_totp().unwrap();
        assert_eq!(
            lock.state.totp.as_ref().unwrap().secret,
            TOTP_KEYRING_MARKER
        );
        // ... yet verification still works, round-tripping through the protector.
        let raw = b32decode(&enrollment.secret);
        assert!(lock.confirm_totp(&hotp(&raw, now_ms() / 30_000)).unwrap());
    }

    #[test]
    fn migrate_totp_secret_upgrades_plaintext_once_protector_available() {
        let (_dir, mut lock) = fresh_lock(); // NullProtector: nothing available yet
        lock.state.totp = Some(TotpState {
            secret: "PLAINBASE32SECRETXXX".to_string(),
            active: false,
        });
        lock.migrate_totp_secret();
        assert_eq!(
            lock.state.totp.as_ref().unwrap().secret,
            "PLAINBASE32SECRETXXX",
            "no protector available -> stays plaintext"
        );

        lock.protector = Box::new(FakeProtector::new()); // keyring "becomes available"
        lock.migrate_totp_secret();
        assert_eq!(
            lock.state.totp.as_ref().unwrap().secret,
            TOTP_KEYRING_MARKER
        );
        assert_eq!(
            lock.unprotect_secret(&lock.state.totp.as_ref().unwrap().secret),
            Some("PLAINBASE32SECRETXXX".to_string())
        );
    }

    #[test]
    fn migrate_totp_secret_never_touches_electron_blob() {
        let dir = tempfile::tempdir().unwrap();
        let mut lock = AuthLock::load_with_protector(dir.path(), Box::new(FakeProtector::new()));
        lock.state.totp = Some(TotpState {
            secret: "enc:v1:some-electron-ciphertext==".to_string(),
            active: true,
        });
        lock.migrate_totp_secret();
        assert_eq!(
            lock.state.totp.as_ref().unwrap().secret,
            "enc:v1:some-electron-ciphertext=="
        );
    }

    // ---- backoff: pure delay curve, then wired-up behavior ----

    #[test]
    fn backoff_delay_curve_grows_and_caps_without_overflow() {
        for f in 0..BACKOFF_AFTER {
            assert_eq!(backoff_delay_ms(f), 0, "no backoff below the threshold");
        }
        assert_eq!(backoff_delay_ms(5), 30_000);
        assert_eq!(backoff_delay_ms(6), 60_000);
        assert_eq!(backoff_delay_ms(7), 120_000);
        assert_eq!(backoff_delay_ms(8), 240_000);
        assert_eq!(backoff_delay_ms(10), 960_000);
        assert_eq!(backoff_delay_ms(11), 1_800_000, "already past the cap");
        assert_eq!(
            backoff_delay_ms(100),
            1_800_000,
            "huge fail counts stay capped, never panic"
        );
    }

    #[test]
    fn backoff_throttles_after_five_failures_then_resets_on_success() {
        let (_dir, mut lock) = fresh_lock();
        for _ in 0..4 {
            lock.record_failure("test:purpose");
        }
        assert_eq!(
            lock.throttle_retry_in("test:purpose"),
            0,
            "below threshold, no backoff yet"
        );

        lock.record_failure("test:purpose"); // 5th failure crosses BACKOFF_AFTER
        let wait = lock.throttle_retry_in("test:purpose");
        assert!(
            wait > 0 && wait <= 30_000,
            "expected ~30s backoff, got {wait}ms"
        );

        lock.record_success("test:purpose");
        assert_eq!(lock.throttle_retry_in("test:purpose"), 0);
    }

    #[test]
    fn backoff_is_independent_per_purpose() {
        let (_dir, mut lock) = fresh_lock();
        for _ in 0..5 {
            lock.record_failure("auth:login");
        }
        assert!(lock.throttle_retry_in("auth:login") > 0);
        assert_eq!(lock.throttle_retry_in("egress:unlock"), 0);
    }

    // ---- roundtrip save/load ----

    #[test]
    fn roundtrip_save_and_load() {
        let dir = tempfile::tempdir().unwrap();
        let real_code;
        let secret_b32;
        {
            let mut lock = AuthLock::load_with_protector(dir.path(), Box::new(NullProtector));
            lock.set_passphrase("hunter2-fake").unwrap();
            let enrollment = lock.enroll_totp().unwrap();
            secret_b32 = enrollment.secret.clone();
            let raw = b32decode(&enrollment.secret);
            real_code = hotp(&raw, now_ms() / 30_000);
            assert!(lock.confirm_totp(&real_code).unwrap());
        } // lock dropped — nothing but the file on disk survives

        let reloaded = AuthLock::load_with_protector(dir.path(), Box::new(NullProtector));
        let status = reloaded.status();
        assert!(status.configured);
        assert!(status.totp);
        assert!(reloaded.verify_passphrase("hunter2-fake"));
        assert!(!reloaded.verify_passphrase("wrong"));
        // the plaintext-fallback secret round-trips as plaintext on disk
        // (NullProtector on both ends) — a fresh TOTP code still verifies.
        let raw = b32decode(&secret_b32);
        assert!(reloaded.verify_totp(&hotp(&raw, now_ms() / 30_000)));
    }

    #[test]
    fn load_on_missing_or_corrupt_file_starts_fresh() {
        let dir = tempfile::tempdir().unwrap();
        // Missing file entirely.
        let lock = AuthLock::load_with_protector(dir.path(), Box::new(NullProtector));
        assert!(!lock.status().configured);

        // Corrupt JSON.
        std::fs::write(dir.path().join(AUTH_FILE_NAME), b"{ not valid json").unwrap();
        let lock = AuthLock::load_with_protector(dir.path(), Box::new(NullProtector));
        assert!(!lock.status().configured);
        assert!(!lock.totp_active());
    }
}
