//! RFC 4226 (HOTP) and RFC 6238 (TOTP) — SHA-1, 30-second step, 6 digits —
//! plus the base32 codec used to encode/decode TOTP secrets. A direct,
//! line-for-line port of `src/main/lib/totp.js`, which `src/main/authlock.js`
//! builds enrollment/verification on top of (ported separately, in
//! `authlock.rs`, which calls back into this module exactly like the JS
//! original imports from `./lib/totp.js`).
//!
//! Pinned two ways:
//! - Byte-for-byte against `tests/auth_fixtures.json`'s `totp[]` and
//!   `b32[]` arrays, generated by the real Node `crypto` module and this
//!   file's JS original — see `fixtures_pin_totp`/`fixtures_pin_b32` below.
//! - Behaviorally against every `describe('hotp'...)` / `describe('totp'...)`
//!   / `describe('base32'...)` assertion in `test/authlock.test.js` — see
//!   the tests below grouped under the matching `---- ported from ... ----`
//!   comments (`rfc4226_appendix_d_vectors`, `totp_round_trips_*`,
//!   `totp_matches_hotp_*`, and the three `base32_*` tests).
//!
//! ## Why base32 is hand-rolled instead of using the `base32` crate
//! `lib/totp.js`'s `b32decode` is deliberately lenient: it strips any
//! trailing run of `=`, uppercases before matching, and silently *skips*
//! any character that isn't in the alphabet rather than failing the whole
//! decode (`test/authlock.test.js`'s `ignores trailing padding` and
//! `decodes lowercase input identically` pin exactly this). The `base32`
//! crate on crates.io (also a Cargo.toml dependency, added for this slice)
//! instead decodes fixed 8-character blocks against a lookup table sized
//! for one exact, pre-chosen padding scheme, and returns `None` on the
//! first unrecognized byte — including a bare `=` when the non-padded
//! `Rfc4648 { padding: false }` alphabet is selected, which is exactly the
//! shape `b32encode` below produces and the padding test then appends
//! `=` characters to. Rather than fight the crate's stricter contract (or
//! silently diverge from the JS behavior these vitest cases pin), this is
//! a direct transliteration of the JS bit-accumulator: it reproduces the
//! exact leniency instead of hoping a general-purpose crate's edge cases
//! happen to line up. The `base32` dependency stays in Cargo.toml (out of
//! this slice's scope to remove) but is unused by design — noted here so
//! the choice reads as deliberate, not an oversight.

use hmac::{Hmac, KeyInit, Mac};
use sha1::Sha1;

type HmacSha1 = Hmac<Sha1>;

/// RFC 4648 base32 alphabet — matches `lib/totp.js`'s `B32` constant
/// exactly (no padding character; encode never emits one).
const B32_ALPHABET: &[u8; 32] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";

/// Base32-encode `buf` (RFC 4648 alphabet, unpadded). Port of
/// `lib/totp.js`'s `b32encode`: a straightforward 8-bits-in/5-bits-out
/// accumulator, left-padding the final partial group with zero bits
/// (`val << (5 - bits)`) exactly like the JS original.
pub fn b32encode(buf: &[u8]) -> String {
    let mut bits: u32 = 0;
    let mut val: u32 = 0;
    let mut out = String::with_capacity((buf.len() * 8).div_ceil(5));
    for &b in buf {
        val = (val << 8) | u32::from(b);
        bits += 8;
        while bits >= 5 {
            out.push(B32_ALPHABET[((val >> (bits - 5)) & 31) as usize] as char);
            bits -= 5;
        }
    }
    if bits > 0 {
        out.push(B32_ALPHABET[((val << (5 - bits)) & 31) as usize] as char);
    }
    out
}

/// Base32-decode `s`, tolerant like `lib/totp.js`'s `b32decode`: strips any
/// trailing run of `=` first (`s.replace(/=+$/, '')`), matches
/// case-insensitively (`.toUpperCase()`), and silently skips any character
/// not in the alphabet — including a `=` that isn't part of a trailing run
/// — rather than erroring (`if (i < 0) continue`). See the module doc
/// comment for why this exact leniency is preserved by hand-rolling rather
/// than delegated to a stricter crate.
pub fn b32decode(s: &str) -> Vec<u8> {
    let mut bits: u32 = 0;
    let mut val: u32 = 0;
    let mut out = Vec::with_capacity(s.len() * 5 / 8);
    for c in s.trim_end_matches('=').chars() {
        let upper = c.to_ascii_uppercase();
        let Some(idx) = B32_ALPHABET.iter().position(|&a| a as char == upper) else {
            continue; // not in the alphabet — skip, don't fail the whole decode
        };
        val = (val << 5) | idx as u32;
        bits += 5;
        if bits >= 8 {
            out.push(((val >> (bits - 8)) & 255) as u8);
            bits -= 8;
        }
    }
    out
}

/// HOTP (RFC 4226): HMAC-SHA1 over the 8-byte big-endian `counter`,
/// dynamically truncated per §5.3, mod 1e6, zero-padded to 6 digits. Direct
/// port of `lib/totp.js`'s `hotp`. `new_from_slice` on an HMAC key never
/// fails for any key length (RustCrypto hashes down/zero-pads internally
/// per RFC 2104 §2) — the `expect` documents that rather than guarding a
/// reachable error.
pub fn hotp(secret: &[u8], counter: u64) -> String {
    let mut mac = HmacSha1::new_from_slice(secret).expect("HMAC-SHA1 accepts a key of any length");
    mac.update(&counter.to_be_bytes());
    let digest = mac.finalize().into_bytes();
    let offset = (digest[19] & 0x0f) as usize;
    let truncated = u32::from_be_bytes([
        digest[offset],
        digest[offset + 1],
        digest[offset + 2],
        digest[offset + 3],
    ]) & 0x7fff_ffff;
    format!("{:06}", truncated % 1_000_000)
}

/// Current time as Unix epoch milliseconds — the Rust equivalent of
/// `Date.now()`, which `lib/totp.js`'s `totp()` uses as its default `at`
/// and `authlock.js`'s `verifyTotp()` uses inline to derive its ±1-step
/// window. Falls back to the epoch itself (never panics) if the system
/// clock somehow reports a time before 1970 — a real device clock never
/// does this, but a library function silently misbehaving instead of
/// panicking on a clock fault is the safer failure mode here (worst case:
/// TOTP verification fails closed, exactly as if the code were wrong).
pub fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand::Rng;

    // ---- cross-language fixture pin (src-tauri/tests/auth_fixtures.json,
    // generated by the real Node `crypto` module + this file's JS
    // original) ----

    const FIXTURES_JSON: &str = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/auth_fixtures.json"
    ));

    #[derive(serde::Deserialize)]
    struct TotpFixture {
        secret: String,
        at_ms: u64,
        code: String,
    }

    #[derive(serde::Deserialize)]
    struct B32Fixture {
        hex: String,
        b32: String,
        decoded_hex: String,
    }

    #[derive(serde::Deserialize)]
    struct Fixtures {
        totp: Vec<TotpFixture>,
        b32: Vec<B32Fixture>,
    }

    /// Minimal, trusting hex decoder for fixture data only — fixtures are
    /// generated, not hand-typed, so this panics on malformed input rather
    /// than handling it gracefully (contrast `authlock.rs`'s production
    /// `hex_decode`, which must fail closed on untrusted disk contents).
    fn fixture_hex(s: &str) -> Vec<u8> {
        assert!(
            s.len().is_multiple_of(2),
            "fixture hex string has odd length: {s}"
        );
        (0..s.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("fixture hex digit"))
            .collect()
    }

    fn load_fixtures() -> Fixtures {
        serde_json::from_str(FIXTURES_JSON).expect("auth_fixtures.json parses")
    }

    #[test]
    fn fixtures_pin_totp() {
        let fx = load_fixtures();
        assert!(!fx.totp.is_empty(), "fixture file has no totp[] entries");
        for f in &fx.totp {
            let secret = b32decode(&f.secret);
            // TOTP is HOTP at the 30-second step (RFC 6238); `verify_totp`
            // in authlock.rs derives that step inline, so pin the fixture
            // through `hotp` directly rather than a thin `totp` wrapper.
            assert_eq!(
                hotp(&secret, f.at_ms / 30_000),
                f.code,
                "totp mismatch: secret={} at_ms={}",
                f.secret,
                f.at_ms
            );
        }
    }

    #[test]
    fn fixtures_pin_b32() {
        let fx = load_fixtures();
        assert!(!fx.b32.is_empty(), "fixture file has no b32[] entries");
        for f in &fx.b32 {
            let raw = fixture_hex(&f.hex);
            assert_eq!(
                b32encode(&raw),
                f.b32,
                "b32encode mismatch for hex {}",
                f.hex
            );
            assert_eq!(
                b32decode(&f.b32),
                fixture_hex(&f.decoded_hex),
                "b32decode mismatch for b32 {}",
                f.b32
            );
        }
    }

    // ---- RFC 4226 Appendix D — ported from test/authlock.test.js's
    // `describe('hotp (RFC 4226)')` ----

    #[test]
    fn rfc4226_appendix_d_vectors() {
        // "Secret is ASCII string '12345678901234567890'" — RFC 4226 App. D.
        let secret = b"12345678901234567890";
        let vectors: [(u64, &str); 10] = [
            (0, "755224"),
            (1, "287082"),
            (2, "359152"),
            (3, "969429"),
            (4, "338314"),
            (5, "254676"),
            (6, "287922"),
            (7, "162583"),
            (8, "399871"),
            (9, "520489"),
        ];
        for (counter, expected) in vectors {
            assert_eq!(hotp(secret, counter), expected, "counter {counter}");
        }
    }

    // ---- ported from test/authlock.test.js's `describe('base32')` ----

    #[test]
    fn base32_encode_decode_round_trips_random_secrets() {
        for i in 0..20usize {
            let mut buf = vec![0u8; 1 + i]; // exercise every padding length
            rand::rng().fill_bytes(&mut buf);
            assert_eq!(
                b32decode(&b32encode(&buf)),
                buf,
                "round-trip failed at len {}",
                1 + i
            );
        }
    }

    #[test]
    fn base32_decodes_lowercase_input_identically() {
        let mut buf = [0u8; 20];
        rand::rng().fill_bytes(&mut buf);
        let enc = b32encode(&buf);
        assert_eq!(b32decode(&enc.to_lowercase()), b32decode(&enc));
    }

    #[test]
    fn base32_ignores_trailing_padding() {
        let mut buf = [0u8; 20];
        rand::rng().fill_bytes(&mut buf);
        let enc = b32encode(&buf);
        assert_eq!(b32decode(&format!("{enc}===")), buf);
    }
}
